google_analytics: UA-72691106-1

title: "Samuel Hinton"
global_title: "Samuel Hinton"
baseurl: ""
url: "https://cosmiccoding.com.au"
content_path: "static/img/blog"
img_path: 'static/img/'
repository: samreay/samreay
github: [metadata]

# author
author:
  name: 'Samuel Hinton'
  first_name: 'Samuel'
  last_name: 'Hinton'
  email: 'samuelreay@gmail.com'
  insta_username: 'samreay'
  github_username: 'samreay'
  twitter_username: 'samreayh'
  linkedin_username: 'samuelreay'
  head_img: 'static/img/landing/face.jpg'
  profile_img: 'static/img/landing/profile.jpg'


sections:
  - id: about
    tpl: about.html
  - id: latest
    tpl: latest.html
  - id: books
    tpl: books.html
  - id: newsletter
    tpl: newsletter.html
  - id: tutorials
    tpl: tutorials.html
  - id: courses
    tpl: courses.html
  - id: other
    tpl: other.html
    

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from


exclude: 
  - styles/index.css
  - styles/syntax.css
  - package.json
  - package-lock.json
  - postcss.config.js
  - readme.md
  - node_modules
