title: "CosmicCoding"
baseurl: ""
url: "http://cosmiccoding.com.au"
content_path: "static/img/blog"
img_path: 'http://cosmiccoding.com.au/static/img/'
repository: samreay/samreay.github.io
github: [metadata]

# author
author:
  name: 'Samuel Hinton'
  first_name: 'Samuel'
  last_name: 'Hinton'
  email: 'samuelreay@gmail.com'
  facebook_username: 'samuelreay'
  github_username: 'samreay'
  head_img: 'static/img/landing/face.jpg'

# sections
sections:
  - id: 'about-me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'academia'
    name: 'Academia'
    tpl: 'academia.html'
    css: 'academia'

  - id: 'cta'
    name: 'Talks'
    tpl: 'cta.html'
    css: 'cta'

  - id: 'personal'
    name: 'Personal'
    tpl: 'personal.html'
    css: 'personal'


#disqus:
#  name: samreay
#  public_key: MYiCDJWlzq6IEkSXbAflF3DLdf1RmcjWGoOc3TBI3LoRNkmAemEiXyWhX0wOYPU8

# google analytics
ga:
  id: UA-72691106-1

# Build settings
encoding: "utf-8"
exclude:
    - node_modules

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
