title: "Samuel Hinton"
baseurl: "/"
url: "https://samreay.github.io"
img_path: 'https://samreay.github.io/static/img/blog'
#url: "http://127.0.0.1:4000"
#img_path: 'http://127.0.0.1:4000/static/img/blog'
repository: samreay/samreay.github.io
github: [metadata]

github:
  url: http://localhost:4000
  
# author
author:
  name: 'Samuel Hinton'
  first_name: 'Samuel'
  last_name: 'Hinton'
  email: 'samuelreay@gmail.com'
  facebook_username: 'samuelreay'
  github_username: 'samreay'
  head_img: 'static/img/landing/face.jpg'

# sections
sections:
  - id: 'about-me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'github'
    name: 'Github'
    tpl: 'github.html'
    css: 'project'

  - id: 'projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'timeline'

  - id: 'trips'
    name: 'Trips'
    tpl: 'trips.html'
    css: 'trips'

  - id: 'blogs'
    name: 'Blogs'
    tpl: 'blogs.html'
    css: 'blogs'

disqus:
  name: samreay
  public_key: MYiCDJWlzq6IEkSXbAflF3DLdf1RmcjWGoOc3TBI3LoRNkmAemEiXyWhX0wOYPU8

# google analytics
ga:
  id: UA-72691106-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
