title: "CosmicCoding"
global_title: "CosmicCoding | Samuel Hinton"
baseurl: ""
url: "https://cosmiccoding.com.au"
content_path: "static/img/blog"
img_path: 'https://cosmiccoding.com.au/static/img/'
repository: samreay/samreay
github: [metadata]

# author
author:
  name: 'Samuel Hinton'
  first_name: 'Samuel'
  last_name: 'Hinton'
  email: 'samuelreay@gmail.com'
  insta_username: 'samreay'
  github_username: 'samreay'
  twitter_username: 'samreayh'
  linkedin_username: 'samuelreay'
  head_img: 'static/img/landing/face.jpg'
  profile_img: 'static/img/landing/profile.jpg'

courses:
  statistics: https://www.udemy.com/course/python-for-statistical-analysis/?referralCode=76158B46FA5EB57C38EB
  datamanip: https://www.udemy.com/course/data-manipulation-in-python/?referralCode=76D0B64A481951B29E77
# sections
sections:
  - id: 'about-me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'academia'
    name: 'Academia'
    tpl: 'academia.html'
    css: 'academia'

#  - id: 'cta'
#    name: 'Talks'
#    tpl: 'cta.html'
#    css: 'cta'
#  - id: 'personal'
#    name: 'Personal'
#    tpl: 'personal.html'
#    css: 'personal'


#disqus:
#  name: samreay
#  public_key: MYiCDJWlzq6IEkSXbAflF3DLdf1RmcjWGoOc3TBI3LoRNkmAemEiXyWhX0wOYPU8

# google analytics
ga:
  id: UA-72691106-1

# Build settings
encoding: "utf-8"
exclude:
    - node_modules

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

plugins:
  - jekyll-redirect-from