// Hand-authored source of truth for the recommendation flowchart. The Astro
// page (`src/pages/reviews/flowchart.astro`) feeds this through
// `src/lib/flowchart-layout.ts` to produce dagre-positioned xyflow nodes.
//
// IDs are string-stable: edges reference them and the future migration off
// the Figma board (~150 nodes) expects to add more nodes incrementally
// without renumbering. Two parallel arrays of typed nodes (decisions and
// books) instead of a single polymorphic array, because authoring is easier
// when "another decision" and "another book" are visually distinct sections.

export interface DecisionNode {
  id: string;
  /** Headline question shown inside the diamond. */
  prompt: string;
  /** Agent-readable question that expands on `prompt`. Not rendered in the
   *  UI; used by automated tools to decide which branch a book belongs on.
   *  Phrase it as a yes/no or multiple-choice question whose answers map
   *  directly to the outgoing edges of this node. */
  description?: string;
  /** Pick a colour from the Tailwind 500 palette for the node's border
   *  and background tint. Omit for the default `'gray'`. */
  color?: PaletteColor;
  /** Layout escape hatch — if set, dagre's computed position is ignored and
   *  this top-left coordinate is used instead. Use sparingly; intended for
   *  the rare node that has to sit in a hand-tuned spot (section anchors,
   *  group headers, the very top of the tree). */
  pinned?: { x: number; y: number };
  /** Render the pill at 2x its default 320x90 footprint. Reserved for
   *  visual anchors like the "Start Here!" entry point — bumping this on
   *  a generic question would just push neighbours apart for no editorial
   *  reason. Omit for the default 'normal'. */
  size?: 'normal' | 'large';
}

export interface BookNode {
  id: string;
  /** Matches the review collection entry id, i.e. `content/reviews/<reviewId>/`. */
  reviewId: string;
  /** See DecisionNode.pinned. */
  pinned?: { x: number; y: number };
}

/**
 * Named palette colours used for both edges and decision-node accents.
 * Each maps to a Tailwind 500-shade hex in `EDGE_PALETTE` inside
 * `flowchart-layout.ts`. Add new entries by editing both this union and
 * that map — the two are intentionally kept in lockstep so a typo here
 * fails type-checking instead of silently falling back to the default.
 */
export type PaletteColor =
  | 'red'
  | 'orange'
  | 'amber'
  | 'yellow'
  | 'lime'
  | 'green'
  | 'emerald'
  | 'teal'
  | 'cyan'
  | 'sky'
  | 'blue'
  | 'indigo'
  | 'violet'
  | 'purple'
  | 'fuchsia'
  | 'pink'
  | 'red'
  | 'gray';

/** @deprecated Use `PaletteColor`. Kept as an alias because the union
 *  is now shared with decision-node accents, not just edges. */
export type EdgeColor = PaletteColor;

/**
 * Edge path style. Friendly names that the layout helper maps onto
 * xyflow's built-in edge renderers (`'bezier'` → xyflow's `'default'`).
 */
export type EdgeType = 'bezier' | 'simplebezier' | 'smoothstep' | 'step' | 'straight';

export interface FlowchartEdge {
  id: string;
  source: string;
  target: string;
  /** Answer text that labels the edge ("I will survive", etc.). */
  label?: string;
  /** Pick a colour from the Tailwind 500 palette. Omit for the default
   *  accent green. */
  color?: PaletteColor;
  /** Override the path style for this single edge. Falls back to
   *  `FlowchartData.defaultEdgeType` when omitted. */
  type?: EdgeType;
}

export interface FlowchartData {
  decisions: DecisionNode[];
  books: BookNode[];
  edges: FlowchartEdge[];
  /** Path style applied to every edge that doesn't set its own `type`.
   *  Defaults to `'bezier'` if omitted. */
  defaultEdgeType?: EdgeType;
}

// The arrays below were generated by `.cursor/skills/parse-flowchart` from
// the Story-Finder-big.jpg Figma export (216 nodes / 231 edges). Re-running
// the skill rewrites only these arrays — keep the type definitions and
// hand-tuned `pinned` overrides above intact.
export const flowchart: FlowchartData = {
  defaultEdgeType: 'bezier',
  decisions: [
    {
      id: 'd_start',
      prompt: 'Start Here!',
      description: 'Entry point of the flowchart. Always follow the outgoing edge to begin navigating recommendations.',
      color: 'amber',
      size: 'large',
      pinned: { x: 0, y: 0 },
    },
    {
      id: 'd_will_you_die',
      prompt: 'Will you die without stats or a system?',
      description:
        'Does the book need a visible numbers-based progression system (levelling, stat screens, skill trees), or can progression be implicit or cultivation-style?',
    },
    {
      id: 'd_ai_can_spend_points_and_buy_yo',
      prompt: 'AI can spend points and buy you nice shit?',
      description:
        "Does the AI companion in the book have autonomous agency over the protagonist's character build — spending points, buying gear, or making levelling decisions on their behalf?",
    },
    {
      id: 'd_alright_you_do_you_buddy',
      prompt: 'Alright. You do you, buddy.',
      description:
        'Does the book feature an effectively unkillable protagonist who survives through sheer tenacity rather than power?',
    },
    {
      id: 'd_are_weird_creature_companions',
      prompt: 'Are weird creature companions good?',
      description: 'Does the book feature memorable non-human companion creatures as a significant element?',
    },
    {
      id: 'd_back_to_combat_training_then',
      prompt: 'Back to combat training then?',
      description:
        "The reader is in the cultivation branch but doesn't want crafting. What combat style does the book lean into?",
    },
    {
      id: 'd_be_specific',
      prompt: 'Be specific!',
      description:
        'The reader wants a crafting-focused LitRPG set in a science-knowledge-exploiting world. Which specific craft does the book focus on?',
    },
    {
      id: 'd_but_i_want_a_focus_on',
      prompt: 'But I want a focus on...',
      description:
        'The reader wants an isekai/portal-fantasy book where humanity is broadly accepted. What should the narrative focus on — an ensemble group, a female MC, or a male MC?',
    },
    {
      id: 'd_crafting_trading_focus',
      prompt: 'Crafting / trading focus?',
      description:
        "The reader is in the card-game fantasy sub-tree but doesn't want cards. Do they want a crafting/trading focus, or do they crave violence?",
    },
    {
      id: 'd_please_explain',
      prompt: 'Please explain.',
      description:
        'The reader chose something other than isekai or system apocalypse. Is it a VRMMO, or an original/real world setting?',
    },
    {
      id: 'd_its_gonna_be',
      prompt: "It's gonna be...",
      description:
        'The reader wants to climb a dungeon. What kind of dungeon-climbing story do they want?',
    },
    {
      id: 'd_acredited_right',
      prompt: 'Accredited, right?',
      description:
        'The reader wants a teacher protagonist. What kind of teacher is the MC — a child prodigy, a fraud, or a scientist?',
    },
    {
      id: 'd_deliver_pain_via_weapons_or_ma',
      prompt: 'Deliver pain via weapons or magic?',
      description: "In this system-apocalypse book, what is the protagonist's primary combat approach?",
    },
    {
      id: 'd_do_you_like_a_good_crafting_se',
      prompt: 'Do you like a good crafting session?',
      description:
        'Does the book feature significant crafting mechanics alongside its magic-school or learning focus, and how central is crafting?',
    },
    {
      id: 'd_gimme_the_gimmick',
      prompt: 'Gimme the gimmick!',
      description:
        "The reader wants a magic-school book with a bit of crafting. What is the protagonist's unique magical gimmick?",
    },
    {
      id: 'd_do_you_scream_for_joy_every_ti',
      prompt: "Do you scream for joy every time there's a pop culture reference?",
      description: 'How prominent are pop-culture references and easter eggs in this LitRPG?',
    },
    {
      id: 'd_dungeon_s_focus_is',
      prompt: "Dungeon's focus is...",
      description: "The reader wants to play as a dungeon core. What is the dungeon's primary thematic focus or goal?",
    },
    {
      id: 'd_dungeons_id_love_to',
      prompt: "Dungeons... I'd love to...",
      description:
        "The reader wants a dungeon-focused book. What is the protagonist's relationship with the dungeon — explore it, be one, climb one, be a minion, run one, or die in one?",
    },
    {
      id: 'd_enabled_because',
      prompt: 'Enabled because...',
      description: 'The reader wants gratuitous violence. What mechanism enables or frames that violence?',
    },
    {
      id: 'd_epic_fantasy_or_traditional_cu',
      prompt: 'Epic fantasy or traditional cultivation?',
      description:
        'The reader is in the cultivation sub-tree. Does the book offer fast-paced traditional xianxia/dao cultivation or a slower-paced epic fantasy cultivation style?',
    },
    {
      id: 'd_families_are',
      prompt: 'Families are...',
      description:
        'How are family relationships portrayed in the book — wholesome and supportive, or confusing/absent?',
    },
    {
      id: 'd_fanfic_of',
      prompt: 'Fanfic of...',
      description:
        'The reader wants a fan-fiction or heavily fan-fiction-adjacent cyberpunk story. Which source material does it draw from?',
    },
    {
      id: 'd_fantasy_or_scifi',
      prompt: 'Fantasy or Scifi?',
      description:
        'The reader wants a non-isekai, non-apocalypse LitRPG set in an original world. Is the setting fantasy or sci-fi?',
    },
    {
      id: 'd_thank_god_youre_a',
      prompt: "Thank god you're a...",
      description:
        "The reader wants combat-adjacent science-exploit content. What is the protagonist's role — farmer, dungeon-explorer, or teacher?",
    },
    {
      id: 'd_chill_sprinkle',
      prompt: 'With a sprinkle of...',
      description:
        'The reader wants a chill science-exploit LitRPG. What flavour of chill — fishing or sass?',
    },
    {
      id: 'd_female_mc',
      prompt: 'Female MC?',
      description: 'The reader is in the cyberpunk slow-burn sub-tree. Does the book feature a female protagonist?',
    },
    {
      id: 'd_futuristic_sci_fi',
      prompt: 'Futuristic sci-fi?',
      description: 'The reader wants time-skip (not time-loop) stories. Is the book hard/classic sci-fi or cyberpunk?',
    },
    {
      id: 'd_haaaave_you_read_cradle',
      prompt: 'Haaaave you read Cradle?',
      description: 'Has the reader already read the Cradle series by Will Wight?',
    },
    {
      id: 'd_have_you_read_a_lot_of_cultiva',
      prompt: 'Have you read a lot of cultivation? Maybe time for break?',
      description:
        'Has the reader consumed a large amount of cultivation fiction already and might want a lighter break?',
    },
    {
      id: 'd_hell_or_africa',
      prompt: 'Hell or Africa?',
      description:
        'The reader wants cultivation fantasy with plenty of conflict. Which setting backdrop does the book use?',
    },
    {
      id: 'd_how_about_time_loops_time_loop',
      prompt: 'How about time loops? Time loops are cool!',
      description:
        'The reader is in the magic-school sub-tree but is lukewarm on schools. Does the book feature time loops, time skips, or neither?',
    },
    {
      id: 'd_how_do_you_like_your_ears',
      prompt: 'How do you like your ears?',
      description:
        'The reader is in a cultivation sect-life sub-tree. Is the protagonist human or a beast-kin/animal-eared character?',
    },
    {
      id: 'd_how_much_fan_fiction_and_cross',
      prompt: 'How much fan-fiction and crossovers do you want?',
      description:
        'The reader is in the cyberpunk OP-protagonist sub-tree. How much fan-fiction and crossover content does the book contain?',
    },
    {
      id: 'd_how_much_focus_on_learning',
      prompt: 'How much focus on learning?',
      description: 'The reader loves magic schools. How central is the academic/learning component?',
    },
    {
      id: 'd_humanity_is',
      prompt: 'Humanity is...',
      description:
        'The reader chose isekai/portal fantasy. Is the protagonist human, somewhat non-human, or fully non-human?',
    },
    {
      id: 'd_by_how_much',
      prompt: 'By how much?',
      description:
        'The reader wants a non-human isekai protagonist. How non-human is the protagonist — somewhat non-human, or an entirely non-human creature?',
    },
    {
      id: 'd_so_youre_thinking',
      prompt: "So you're thinking...",
      description: 'The reader wants a somewhat-non-human isekai MC. Which type of non-human is the protagonist?',
    },
    {
      id: 'd_i_can_t_craft_because',
      prompt: "I can't craft because...",
      description:
        'The reader wants crafting but something prevents the MC from doing it. What is the obstacle keeping the protagonist from crafting?',
    },
    {
      id: 'd_i_gotchu_fam',
      prompt: 'I gotchu, fam',
      description:
        'Confirmation node: the reader wants a strong-but-not-godlike MC in an original cyberpunk world with no crossovers.',
    },
    {
      id: 'd_i_like',
      prompt: 'I like...',
      description:
        'The reader wants a very strong MC in a combat-focused LitRPG. What specific quirky interest or theme does the book revolve around?',
    },
    {
      id: 'd_i_prefer_mcs_who_are',
      prompt: 'I prefer MCs who are...',
      description: "The reader wants a combat-primary fantasy LitRPG. What is the protagonist's power-level arc?",
    },
    {
      id: 'd_is_combat_the_primary_focus',
      prompt: 'Is combat the primary focus?',
      description:
        'The reader chose a male-MC fantasy isekai. Is combat the dominant theme, or does the protagonist exploit real-world science knowledge instead?',
    },
    {
      id: 'd_like_how_much',
      prompt: 'Like... how much?',
      description: 'The reader is in cultivation and wants some sci-fi flavour. How much sci-fi is mixed in?',
    },
    {
      id: 'd_maybe_some_cultivation_instead',
      prompt: 'Maybe some cultivation instead?',
      description:
        "The reader doesn't need a LitRPG stats system. Does the book feature cultivation-style progression?",
    },
    {
      id: 'd_mc_specialises_in',
      prompt: 'MC specialises in...',
      description: 'The reader wants a female-MC isekai. What does the protagonist specialise in?',
    },
    {
      id: 'd_mtg_is',
      prompt: 'MtG is...',
      description:
        'The reader is in the serious-tone magic-school sub-tree. Does the book feature Magic: the Gathering as a core element?',
    },
    {
      id: 'd_okay_but_magic_schools_are_coo',
      prompt: 'Okay, but magic schools are cool, right?',
      description: 'The reader rejected cultivation. How prominently does a magic school feature in the book?',
    },
    {
      id: 'd_op_protag',
      prompt: 'OP protag?',
      description: 'The reader is in the cyberpunk sub-tree. How overpowered is the protagonist?',
    },
    {
      id: 'd_opness',
      prompt: 'OPness',
      description: 'The reader chose magic as their combat style. How overpowered is the magic-wielding protagonist?',
    },
    {
      id: 'd_howd_they_manage_that',
      prompt: "How'd they manage that?",
      description:
        'The reader wants an OP-from-day-one magic protagonist. What mechanism made them so powerful so fast?',
    },
    {
      id: 'd_how_dat',
      prompt: 'How dat?',
      description:
        'The reader wants a protagonist who becomes OP within the first couple of books. What is the specific mechanism?',
    },
    {
      id: 'd_organization_or_character_poli',
      prompt: 'Organization or character politics?',
      description:
        'The reader loves time loops and is in the magic-school sub-tree. How prominent is political or organizational intrigue?',
    },
    {
      id: 'd_panam_or_judy',
      prompt: 'Panam or Judy?',
      description:
        'The reader chose sci-fi. This is a Cyberpunk 2077 personality-sieve used to route toward different cyberpunk sub-genres.',
    },
    {
      id: 'd_pick_between',
      prompt: 'Pick between...',
      description:
        'The reader wants a magic school as a setting without heavy academic focus. Which sub-genre does the book fall into?',
    },
    {
      id: 'd_pick_your_backdrop',
      prompt: 'Good and bad are...',
      description:
        'The reader is in a non-LitRPG traditional fantasy sub-tree. How does the book treat morality — black and white, many shades of colour, or complex?',
    },
    {
      id: 'd_interesting_tell_me_more',
      prompt: 'Interesting, tell me more.',
      description:
        'The reader wants complex morality in their traditional fantasy. What angle does the book take on that complexity?',
    },
    {
      id: 'd_pick_your_gimmick',
      prompt: 'Pick your gimmick!',
      description:
        "The reader wants a violence-specialising female MC in an isekai. What is the protagonist's combat gimmick?",
    },
    {
      id: 'd_pick_your_setting',
      prompt: 'Pick your setting',
      description: 'The reader wants a male-MC isekai. What is the setting type?',
    },
    {
      id: 'd_sassy_ai_in_your_head',
      prompt: 'Sassy AI in your head?',
      description:
        "The reader wants a female-MC cyberpunk story. Does the book feature a sassy AI companion living in the protagonist's head?",
    },
    {
      id: 'd_sassy_cat_companion',
      prompt: 'Sassy Cat Companion?',
      description: 'The reader wants a fists-and-feet combat style. Does the book feature a sassy cat companion?',
    },
    {
      id: 'd_scifi_or_fantasy',
      prompt: 'Scifi or Fantasy?',
      description: 'The reader has read a lot of cultivation and wants more. Which flavour does the book take?',
    },
    {
      id: 'd_should_romance_be_a_central_th',
      prompt: 'Should romance be a central theme?',
      description: 'The reader is in the multi-MC cyberpunk sub-tree. Is romance a central theme?',
    },
    {
      id: 'd_slice_of_life',
      prompt: 'Slice of life?',
      description: 'The reader is in the crafting/trading sub-tree. How prominent is slice-of-life pacing?',
    },
    {
      id: 'd_slow_burn_or_power_fantasy',
      prompt: 'Slow burn or power fantasy?',
      description:
        'The reader chose original fantasy. Does the book feature slow character growth or rapid power escalation?',
    },
    {
      id: 'd_specifically',
      prompt: 'Specifically...',
      description:
        'The reader wants a non-violent specialisation for their female isekai MC. What does the protagonist specialise in?',
    },
    {
      id: 'd_system_apocalypse_or_isekai',
      prompt: 'System apocalypse, or isekai?',
      description:
        'The reader wants a LitRPG with numbers. Which sub-genre does the book fall into — system apocalypse, isekai/portal fantasy, original world, or VRMMO?',
    },
    {
      id: 'd_theme',
      prompt: 'Theme?',
      description:
        "The reader is in the cultivation crafting/trading branch and craves more edge. What is the book's dark theme — gratuitous violence, a new beginning, or necromancy?",
    },
    {
      id: 'd_time_loops_or_crunch',
      prompt: 'Time loops or crunch?',
      description:
        'The reader chose a video-game setting. Does the book focus on time-loop mechanics or video-game-crunch grind?',
    },
    {
      id: 'd_vibe_check',
      prompt: 'Chill, Craft, Survive or Fightish?',
      description:
        'The reader wants a LitRPG where the MC exploits real-world science knowledge. What is the secondary vibe — chill slice-of-life, crafting, survival, or combat-adjacent?',
    },
    {
      id: 'd_we_exploring',
      prompt: 'We exploring...',
      description:
        'The reader wants a cultivation fantasy with exploration. What is the primary focus of the exploration?',
    },
    {
      id: 'd_weapon_preference',
      prompt: 'Weapon Preference',
      description:
        'The reader chose weapons as their combat style. Does the protagonist prefer melee or ranged combat?',
    },
    {
      id: 'd_weapon_preference_electric_boo',
      prompt: 'Weapon Preference... electric boogaloo',
      description: 'The reader wants melee weapons. Which specific melee weapon does the protagonist use?',
    },
    {
      id: 'd_what_about_tone_something_ligh',
      prompt: 'What about tone? Something light? Serious?',
      description: "The reader wants a slow-burn original fantasy. What is the book's tone?",
    },
    {
      id: 'd_what_s_better',
      prompt: "What's better?",
      description: 'The reader wants a very non-human isekai protagonist. What type of creature is the protagonist?',
    },
    {
      id: 'd_arms_are',
      prompt: 'Arms are...',
      description:
        'The reader wants a very non-human isekai protagonist. Does the creature have arms, consider arms overrated, or find arms stupid?',
    },
    {
      id: 'd_pick_your_harmless_creature',
      prompt: 'Pick your harmless creature',
      description:
        'The reader wants an armless non-human isekai protagonist. Which armless creature does the MC reincarnate as?',
    },
    {
      id: 'd_whats_your_kink',
      prompt: "What's your kink?",
      description:
        'The reader is in the weird-creature-companions sub-tree. What flavour of "weird" does the book lean into?',
    },
    {
      id: 'd_whoa_easy_there_so_a_strong_bu',
      prompt: 'Whoa, easy there. So a strong but not godlike MC in an original cyberpunk world?',
      description:
        'Confirmation node: does the book feature a strong-but-not-godlike MC in an original cyberpunk world with no crossovers or pop culture references?',
    },
    {
      id: 'd_with_a_focus_on',
      prompt: 'With a focus on...',
      description:
        "The reader is in a sci-fi/superhero branch from the magic-school sub-tree. What is the book's primary focus?",
    },
    {
      id: 'd_with_extra_focus_on',
      prompt: 'With extra focus on...',
      description: 'The reader is in the isekai group-focused sub-tree. What is the extra focus?',
    },
    {
      id: 'd_with_plenty_of',
      prompt: 'With plenty of...',
      description: 'The reader wants a cultivation fantasy. What should there be plenty of in the book?',
    },
    {
      id: 'd_you_like_cards',
      prompt: 'You like cards?',
      description: 'The reader is in a fantasy LitRPG sub-tree. Does the book feature card-based magic systems?',
    },
    {
      id: 'd_your_mcs_are',
      prompt: 'Your MCs are...',
      description:
        'The reader wants exploration-focused cultivation with wholesome families. Which MC pairing does the book feature?',
    },
    {
      id: 'd_your_mcs_are_2',
      prompt: 'Your MCs are...',
      description:
        'The reader wants cultivation with confusing or absent family relationships. Which MC pairing does the book feature?',
    },
    {
      id: 'd_wtf_dark_enough',
      prompt: 'WTF. Is this timeline not dark enough?',
      description: 'The reader chose a dark cyberpunk vibe and wants things even darker. How extreme is the darkness?',
    },
    {
      id: 'd_pick_your_setting_2',
      prompt: 'Give me something. The world?',
      description:
        "The reader is in the time-loops sub-tree but doesn't want time loops. What setting does the book use?",
    },
    {
      id: 'd_movie_analogy',
      prompt: 'Movie analogy?',
      description: 'The reader wants a sci-fi book. Which movie does the book most resemble in tone and premise?',
    },
    {
      id: 'd_but_this_world',
      prompt: 'But...',
      description: 'The reader wants a book set in the real world. What is their specific taste?',
    },
    // De-duplicated branches: each new node below replaces a label that
    // used to fork to multiple books from the same parent decision.
    {
      id: 'd_spear_style',
      prompt: 'Spear-wielder is...',
      description:
        'The reader chose spear as their weapon. What kind of spear-wielding protagonist does the book feature?',
    },
    {
      id: 'd_axe_style',
      prompt: 'And the axe-haver is...',
      description: 'The reader chose axe as their weapon. What kind of axe-wielding protagonist does the book feature?',
    },
    {
      id: 'd_parody_flavour',
      prompt: 'Parody of what, exactly?',
      description:
        'The reader wants a parody in the slow-burn original-fantasy sub-tree. Which genre does the book parody?',
    },
    {
      id: 'd_crafting_companion',
      prompt: 'Craft alongside...',
      description:
        'The reader loves crafting sessions in a magic-school or learning context. What kind of protagonist is the crafter?',
    },
    {
      id: 'd_shapeshift_into',
      prompt: 'Shapeshift into...',
      description:
        'The reader chose shapeshifting as their female-MC isekai gimmick. What does the MC shapeshift into?',
    },
    {
      id: 'd_team_squad',
      prompt: 'Your squad is...',
      description:
        "The reader wants a group-focused isekai with team combat. What is the composition of the protagonist's squad?",
    },
    {
      id: 'd_small_doses_time',
      prompt: 'Time-bender is...',
      description:
        'The reader wants time loops in small doses within an organisation/politics context. What kind of time-bending protagonist does the book feature?',
    },
    {
      id: 'd_you_got_this',
      prompt: "You've got this and no one else does...",
      description:
        "The reader wants a protagonist who got OP early through lucky drops. What unique advantage does the MC's home base provide?",
    },
    {
      id: 'd_and_in_this_home_you',
      prompt: 'And in this home you...',
      description:
        "The reader wants a protagonist with a secure home base. What is the primary activity in that home?",
    },
    {
      id: 'd_vrmmo_login_as',
      prompt: 'Login as...',
      description: 'The reader wants an old-school VRMMO story. Who does the reader play as inside the game?',
    },
    {
      id: 'd_and_should_be',
      prompt: 'And should be...',
      description:
        'The reader wants a non-human isekai protagonist with arms. What texture/type should those arms be?',
    },
    {
      id: 'd_youd_prefer',
      prompt: "You'd prefer?",
      description:
        'The reader wants a non-human isekai protagonist where arms are overrated. What kind of limb substitute do they prefer?',
    },
    {
      id: 'd_privileged_because',
      prompt: 'You are privileged because...',
      description:
        'The reader wants fast-paced traditional cultivation. What is the protagonist\'s head-start — a brutal upbringing that forged them, or prior-life knowledge from being a Godking?',
      color: 'fuchsia',
    },
    {
      id: 'd_in_one_or_build_one',
      prompt: 'In one or build one?',
      description:
        'The reader wants a cultivation fantasy with plenty of sect content. Do they want to be in a sect, build one, or trademark one?',
    },
  ],
  books: [
    { id: 'b_100th_run', reviewId: '100th_run' },
    { id: 'b_1pct_lifesteal', reviewId: '1percent_lifesteal' },
    { id: 'b_accidental_champion', reviewId: 'accidental_champion' },
    { id: 'b_all_the_dust', reviewId: 'all_the_dust' },
    { id: 'b_all_the_skills', reviewId: 'all_the_skills' },
    { id: 'b_antimage', reviewId: 'antimage' },
    { id: 'b_apocalypse_parenting', reviewId: 'apocalypse_parenting' },
    { id: 'b_arcane_ascension', reviewId: 'arcane_ascension' },
    { id: 'b_art_adept', reviewId: 'art_of_the_adept' },
    { id: 'b_aura_overload', reviewId: 'aura_overload' },
    { id: 'b_awaken_online', reviewId: 'awaken_online' },
    { id: 'b_azarinth_healer', reviewId: 'azarinth_healer' },
    { id: 'b_bastion', reviewId: 'bastion' },
    { id: 'b_best_friend_eldritch', reviewId: 'best_friend_eldritch_horror' },
    { id: 'b_beware_chicken', reviewId: 'beware_of_chicken' },
    { id: 'b_bobiverse', reviewId: 'bobiverse' },
    { id: 'b_bog_standard', reviewId: 'bog_standard_isekai' },
    { id: 'b_brightest_shadow', reviewId: 'brightest_shadow' },
    { id: 'b_calamitous_bob', reviewId: 'calamitous_bob' },
    { id: 'b_casteless', reviewId: 'casteless' },
    { id: 'b_changeling', reviewId: 'changeling' },
    { id: 'b_chaos_seeds', reviewId: 'chaos_seeds' },
    { id: 'b_chaotic_craftsman', reviewId: 'chaotic_craftsman' },
    { id: 'b_chronicles_druss', reviewId: 'chronicles_druss' },
    { id: 'b_cinnamon_bun', reviewId: 'cinnamon_bun' },
    { id: 'b_commerce_emperor', reviewId: 'commerce_emperor' },
    { id: 'b_completionist', reviewId: 'completionist_chronicles' },
    { id: 'b_corruption_wielder', reviewId: 'corruption_wielder' },
    { id: 'b_cradle', reviewId: 'cradle' },
    { id: 'b_cyber_dreams', reviewId: 'cyber_dreams' },
    { id: 'b_cybergene', reviewId: 'cybergene' },
    { id: 'b_daily_grind', reviewId: 'the_daily_grind' },
    { id: 'b_dao_magic', reviewId: 'dao_magic' },
    { id: 'b_dawn_void', reviewId: 'dawn_of_the_void' },
    { id: 'b_dcc', reviewId: 'dungeon_crawler_carl' },
    { id: 'b_dear_spellbook', reviewId: 'dear_spellbook' },
    { id: 'b_demon_tree', reviewId: 'demon_tree' },
    { id: 'b_desolada', reviewId: 'desolada' },
    { id: 'b_divine_dungeon', reviewId: 'divine_dungeon' },
    { id: 'b_dotf', reviewId: 'defiance_of_the_fall' },
    { id: 'b_dragons_eye_moons', reviewId: 'beneath_the_dragons_eye_moons' },
    { id: 'b_drr', reviewId: 'die_respawn_repeat' },
    { id: 'b_dungeon_tour_guide', reviewId: 'dungeon_tour_guide' },
    { id: 'b_edge_cases', reviewId: 'edge_cases' },
    { id: 'b_edge_woods', reviewId: 'edge_of_the_woods' },
    { id: 'b_eight', reviewId: 'eight' },
    { id: 'b_elydes', reviewId: 'elydes' },
    { id: 'b_enchanter', reviewId: 'enchanter' },
    { id: 'b_eternal_ephemera', reviewId: 'eternal_ephemera' },
    { id: 'b_fates_parallel', reviewId: 'fates_parallel' },
    { id: 'b_first_law_cult', reviewId: 'first_law_cultivation' },
    { id: 'b_forge_destiny', reviewId: 'forge_of_destiny' },
    { id: 'b_ghost_city', reviewId: 'ghost_in_the_city' },
    { id: 'b_ghost_truthseeker', reviewId: 'ghost_of_the_truthseeker' },
    { id: 'b_godclads', reviewId: 'godclads' },
    { id: 'b_guild_mage', reviewId: 'guild_mage' },
    { id: 'b_heretical_fishing', reviewId: 'heretical_fishing' },
    { id: 'b_how_to_defeat_demon_king', reviewId: 'how_to_defeat_a_demon_king_in_ten_easy_steps' },
    { id: 'b_hwfwm', reviewId: 'hwfwm' },
    { id: 'b_immaculate', reviewId: 'immaculate_collection' },
    { id: 'b_industrial_magic', reviewId: 'industrial_strength_magic' },
    { id: 'b_iron_prince', reviewId: 'iron_prince' },
    { id: 'b_jakes_market', reviewId: 'jakes_magical_market' },
    { id: 'b_just_add_mana', reviewId: 'just_add_mana' },
    { id: 'b_last_physicist', reviewId: 'last_physicist' },
    { id: 'b_legend_arch_magus', reviewId: 'legend_arch_magus' },
    { id: 'b_lightblade', reviewId: 'lightblade' },
    { id: 'b_lightbringer', reviewId: 'lightbringer' },
    { id: 'b_living_forge', reviewId: 'rise_of_the_living_forge' },
    { id: 'b_mage_errant', reviewId: 'mage_errant' },
    { id: 'b_mage_tank', reviewId: 'mage_tank' },
    { id: 'b_mana_mirror', reviewId: 'mana_mirror' },
    { id: 'b_mark_of_the_fool', reviewId: 'mark_of_the_fool' },
    { id: 'b_martial_peak', reviewId: 'martial_peak' },
    { id: 'b_merchant_crab', reviewId: 'merchant_crab' },
    { id: 'b_millenial_mage', reviewId: 'millenial_mage' },
    { id: 'b_minute_mage', reviewId: 'minute_mage' },
    { id: 'b_mother_learning', reviewId: 'mother_of_learning' },
    { id: 'b_neon_dragons', reviewId: 'neon_dragons' },
    { id: 'b_neon_dust', reviewId: 'neon_dust' },
    { id: 'b_never_die_twice', reviewId: 'never_die_twice' },
    { id: 'b_never_fade_away', reviewId: 'never_fade_away' },
    { id: 'b_night_angel', reviewId: 'night_angel' },
    { id: 'b_none_shall_remain', reviewId: 'and_none_shall_remain' },
    { id: 'b_noobtown', reviewId: 'noobtown' },
    { id: 'b_nova_roma', reviewId: 'nova_roma' },
    { id: 'b_odyssey_ethereal', reviewId: 'odyssey_of_the_ethereal' },
    { id: 'b_outcast', reviewId: 'outcast_in_another_world' },
    { id: 'b_path_ascension', reviewId: 'path_ascension' },
    { id: 'b_perfect_run', reviewId: 'perfect_run' },
    { id: 'b_pit_fighter', reviewId: 'pit_fighter' },
    { id: 'b_primal_hunter', reviewId: 'primal_hunter' },
    { id: 'b_queen_mud', reviewId: 'queen_in_the_mud' },
    { id: 'b_quest_academy', reviewId: 'quest_academy' },
    { id: 'b_randidly', reviewId: 'randidly_ghosthound' },
    { id: 'b_reincarnated_farmer', reviewId: 'reincarnated_as_a_farmer' },
    { id: 'b_reluctant_dungeon', reviewId: 'reluctant_dungeon' },
    { id: 'b_remonarch', reviewId: 'remonarch' },
    { id: 'b_rock_falls', reviewId: 'rolling_stone' },
    { id: 'b_rogue_dungeon', reviewId: 'rogue_dungeon' },
    { id: 'b_runebound_professor', reviewId: 'runebound_professor' },
    { id: 'b_runic_artist', reviewId: 'runic_artist' },
    { id: 'b_saintess_skel', reviewId: 'saintess_summons_skeletons' },
    { id: 'b_salvos', reviewId: 'salvos' },
    { id: 'b_scholomance', reviewId: 'scholomance' },
    { id: 'b_seventh_bridge', reviewId: 'seventh_bridge_to_the_heavens' },
    { id: 'b_shadow_slave', reviewId: 'shadow_slave' },
    { id: 'b_shattered_gods', reviewId: 'shattered_gods' },
    { id: 'b_shrubley', reviewId: 'shrubley' },
    { id: 'b_skitterdoc', reviewId: 'skitterdoc' },
    { id: 'b_sky_pride', reviewId: 'sky_pride' },
    { id: 'b_solo_levelling', reviewId: 'solo_levelling' },
    { id: 'b_somnia', reviewId: 'somnia' },
    { id: 'b_soul_relic', reviewId: 'soul_relic' },
    { id: 'b_sovereign_soul', reviewId: 'sovereign_soul' },
    { id: 'b_starbreaker', reviewId: 'starbreaker' },
    { id: 'b_stargazers_war', reviewId: 'stargazers_war' },
    { id: 'b_stray_cat_strut', reviewId: 'stray_cat_strut' },
    { id: 'b_stubborn_grinder', reviewId: 'stubborn_skill_grinder' },
    { id: 'b_super_supportive', reviewId: 'super_supportive' },
    { id: 'b_system_override', reviewId: 'system_override' },
    { id: 'b_thousand_li', reviewId: 'thousand_li' },
    { id: 'b_threadbare', reviewId: 'threadbare' },
    { id: 'b_thrones_fallen', reviewId: 'thrones_of_the_fallen' },
    { id: 'b_titan_hoppers', reviewId: 'titan_hoppers' },
    { id: 'b_tower_apocalypse', reviewId: 'tower_apocalypse' },
    { id: 'b_tower_unbroken', reviewId: 'tower_unbroken' },
    { id: 'b_travellers_trial', reviewId: 'travellers_trial' },
    { id: 'b_ultimate_level', reviewId: 'ultimate_level_one' },
    { id: 'b_umbral_storm', reviewId: 'umbral_storm' },
    { id: 'b_unbound', reviewId: 'unbound' },
    { id: 'b_vainqueur', reviewId: 'vainqueur' },
    { id: 'b_virtuous_sons', reviewId: 'virtuous_sons' },
    { id: 'b_weirkey', reviewId: 'weirkey' },
    { id: 'b_welcome_multiverse', reviewId: 'welcome_to_the_multiverse' },
    { id: 'b_wish_upon_stars', reviewId: 'wish_upon_the_stars' },
    { id: 'b_world_dragons', reviewId: 'the_world_according_to_dragons' },
    { id: 'b_years_apocalypse', reviewId: 'years_of_apocalypse' },
    { id: 'b_practical_evil', reviewId: 'a_practical_guide_to_evil' },
    { id: 'b_buymort', reviewId: 'buymort' },
    { id: 'b_chrysalis', reviewId: 'chrysalis' },
    { id: 'b_dungeon_of_knowledge', reviewId: 'dungeon_of_knowledge' },
    { id: 'b_fifty_shades', reviewId: 'fifty_shades_of_grey' },
    { id: 'b_ironbound', reviewId: 'ironbound' },
    { id: 'b_max_level_archmage', reviewId: 'max_level_archmage' },
    { id: 'b_red_rising', reviewId: 'red_rising' },
    { id: 'b_system_universe', reviewId: 'system_universe' },
    { id: 'b_archmage_coefficient', reviewId: 'the_archmage_coefficient' },
    { id: 'b_hundred_reigns', reviewId: 'the_hundred_reigns' },
    { id: 'b_legend_william', reviewId: 'the_legend_of_william_oh' },
    { id: 'b_turret_mage', reviewId: 'turret_mage' },
    { id: 'b_systema_delenda_est', reviewId: 'systema_delenda_est' },
    { id: 'b_discount_dan', reviewId: 'discount_dan' },
    { id: 'b_speedrunning_the_multiverse', reviewId: 'speedrunning_the_multiverse' },
    { id: 'b_greatest_archmage', reviewId: 'greatest_archmage' },
    { id: 'b_terminate_other_world', reviewId: 'terminate_the_other_world' },
    { id: 'b_keiran_eternal_mage', reviewId: 'keiran_the_eternal_mage' },
    { id: 'b_level_one_god', reviewId: 'level_one_god' },
  ],
  edges: [
    {
      id: 'e_d_your_mcs_are_b_soul_relic',
      source: 'd_your_mcs_are',
      target: 'b_soul_relic',
      label: 'A sister and brother out to see the world',
      color: 'orange',
    },
    {
      id: 'e_d_your_mcs_are_b_weirkey',
      source: 'd_your_mcs_are',
      target: 'b_weirkey',
      label: "A disgruntled double-isekai'd man and his friends",
      color: 'green',
    },
    {
      id: 'e_d_your_mcs_are_b_mana_mirror',
      source: 'd_your_mcs_are',
      target: 'b_mana_mirror',
      label: 'A man on a quest to transition',
      color: 'violet',
    },
    {
      id: 'e_d_families_are_d_your_mcs_are',
      source: 'd_families_are',
      target: 'd_your_mcs_are',
      label: 'Wholesome and supporting',
      color: 'sky',
    },
    {
      id: 'e_d_families_are_d_your_mcs_are_2',
      source: 'd_families_are',
      target: 'd_your_mcs_are_2',
      label: 'Confusing or absent',
      color: 'orange',
    },
    {
      id: 'e_d_your_mcs_are_2_b_world_dragons',
      source: 'd_your_mcs_are_2',
      target: 'b_world_dragons',
      label: 'Indiana Jones and his dragon',
      color: 'violet',
    },
    {
      id: 'e_d_your_mcs_are_2_b_edge_woods',
      source: 'd_your_mcs_are_2',
      target: 'b_edge_woods',
      label: 'Not human and not specified!',
      color: 'green',
    },
    {
      id: 'e_d_sassy_cat_companion_b_dcc',
      source: 'd_sassy_cat_companion',
      target: 'b_dcc',
      label: 'Princess Donut all the way',
      color: 'green',
    },
    {
      id: 'e_d_sassy_cat_companion_b_ghost_truthseeker',
      source: 'd_sassy_cat_companion',
      target: 'b_ghost_truthseeker',
      label: 'Not yet',
      color: 'orange',
    },
    {
      id: 'e_d_we_exploring_d_families_are',
      source: 'd_we_exploring',
      target: 'd_families_are',
      label: 'Fun new places',
      color: 'green',
    },
    {
      id: 'e_d_we_exploring_b_first_law_cult',
      source: 'd_we_exploring',
      target: 'b_first_law_cult',
      label: 'Alchemy',
      color: 'violet',
    },
    {
      id: 'e_d_weapon_preference_electric_boo_b_drr',
      source: 'd_weapon_preference_electric_boo',
      target: 'b_drr',
      label: 'Friends',
      color: 'gray',
    },
    {
      id: 'e_d_weapon_preference_electric_boo_d_spear_style',
      source: 'd_weapon_preference_electric_boo',
      target: 'd_spear_style',
      label: 'Spear',
      color: 'amber',
    },
    {
      id: 'e_d_spear_style_b_randidly',
      source: 'd_spear_style',
      target: 'b_randidly',
      label: 'A solo skill-grinder lost in his own derailing serial',
      color: 'red',
    },
    {
      id: 'e_d_spear_style_b_ultimate_level',
      source: 'd_spear_style',
      target: 'b_ultimate_level',
      label: 'A party-tank-mage-scout',
      color: 'orange',
    },
    {
      id: 'e_d_weapon_preference_electric_boo_d_axe_style',
      source: 'd_weapon_preference_electric_boo',
      target: 'd_axe_style',
      label: 'Axe',
      color: 'red',
    },
    {
      id: 'e_d_axe_style_b_dotf',
      source: 'd_axe_style',
      target: 'b_dotf',
      label: 'A meathead riding a Luck stat through the multiverse',
      color: 'orange',
    },
    {
      id: 'e_d_axe_style_b_dawn_void',
      source: 'd_axe_style',
      target: 'b_dawn_void',
      label: 'A homeless ex-EMT in a buttoned-up trilogy',
      color: 'teal',
    },
    {
      id: 'e_d_weapon_preference_electric_boo_d_sassy_cat_companion',
      source: 'd_weapon_preference_electric_boo',
      target: 'd_sassy_cat_companion',
      label: 'Fists and feet',
      color: 'yellow',
    },
    {
      id: 'e_d_weapon_preference_electric_boo_b_shadow_slave',
      source: 'd_weapon_preference_electric_boo',
      target: 'b_shadow_slave',
      label: 'Katana',
      color: 'sky',
    },
    {
      id: 'e_d_epic_fantasy_or_traditional_cu_d_privileged_because',
      source: 'd_epic_fantasy_or_traditional_cu',
      target: 'd_privileged_because',
      label: 'fastpacedtraditionalplease',
      color: 'fuchsia',
    },
    {
      id: 'e_d_privileged_because_b_sky_pride',
      source: 'd_privileged_because',
      target: 'b_sky_pride',
      label: "You didn't die when living in landfill and eating dirt",
      color: 'fuchsia',
    },
    {
      id: 'e_d_privileged_because_b_speedrunning_the_multiverse',
      source: 'd_privileged_because',
      target: 'b_speedrunning_the_multiverse',
      label: "You're a reincarnated Godking doing speedruns to distract you from an empty existence",
      color: 'violet',
    },
    {
      id: 'e_d_epic_fantasy_or_traditional_cu_b_brightest_shadow',
      source: 'd_epic_fantasy_or_traditional_cu',
      target: 'b_brightest_shadow',
      label: 'Slower paced epic',
      color: 'sky',
    },
    {
      id: 'e_d_theme_d_enabled_because',
      source: 'd_theme',
      target: 'd_enabled_because',
      label: 'Gratuitous violence',
      color: 'red',
    },
    {
      id: 'e_d_theme_b_never_die_twice',
      source: 'd_theme',
      target: 'b_never_die_twice',
      label: 'Necromancy',
      color: 'purple',
    },
    {
      id: 'e_d_enabled_because_b_thrones_fallen',
      source: 'd_enabled_because',
      target: 'b_thrones_fallen',
      label: 'The Dungeon.',
      color: 'amber',
    },
    {
      id: 'e_d_enabled_because_b_stubborn_grinder',
      source: 'd_enabled_because',
      target: 'b_stubborn_grinder',
      label: 'Time loops',
      color: 'orange',
    },
    {
      id: 'e_d_i_can_t_craft_because_b_living_forge',
      source: 'd_i_can_t_craft_because',
      target: 'b_living_forge',
      label: 'NO ONE WILL LEAVE ME ALONE',
      color: 'amber',
    },
    {
      id: 'e_d_i_can_t_craft_because_b_years_apocalypse',
      source: 'd_i_can_t_craft_because',
      target: 'b_years_apocalypse',
      label: 'I need to save the god damned world in a month',
      color: 'sky',
    },
    {
      id: 'e_d_and_should_be_b_shrubley',
      source: 'd_and_should_be',
      target: 'b_shrubley',
      label: 'Leafy',
      color: 'green',
    },
    {
      id: 'e_d_how_do_you_like_your_ears_b_forge_destiny',
      source: 'd_how_do_you_like_your_ears',
      target: 'b_forge_destiny',
      label: 'Uh... Human?',
      color: 'green',
    },
    {
      id: 'e_d_how_do_you_like_your_ears_b_fates_parallel',
      source: 'd_how_do_you_like_your_ears',
      target: 'b_fates_parallel',
      label: 'FLUFFY YOU IDIOT',
      color: 'red',
    },
    {
      id: 'e_d_weapon_preference_d_weapon_preference_electric_boo',
      source: 'd_weapon_preference',
      target: 'd_weapon_preference_electric_boo',
      label: 'I want to smell their breath',
      color: 'orange',
    },
    {
      id: 'e_d_weapon_preference_b_primal_hunter',
      source: 'd_weapon_preference',
      target: 'b_primal_hunter',
      label: 'I dont even want to see my enemy',
      color: 'amber',
    },
    {
      id: 'e_d_hell_or_africa_d_epic_fantasy_or_traditional_cu',
      source: 'd_hell_or_africa',
      target: 'd_epic_fantasy_or_traditional_cu',
      label: 'What sort of question is that?',
      color: 'yellow',
    },
    {
      id: 'e_d_hell_or_africa_b_bastion',
      source: 'd_hell_or_africa',
      target: 'b_bastion',
      label: 'Hell',
      color: 'red',
    },
    {
      id: 'e_d_hell_or_africa_b_tower_unbroken',
      source: 'd_hell_or_africa',
      target: 'b_tower_unbroken',
      label: 'Africa',
      color: 'green',
    },
    {
      id: 'e_d_slice_of_life_d_i_can_t_craft_because',
      source: 'd_slice_of_life',
      target: 'd_i_can_t_craft_because',
      label: 'Sometimes',
      color: 'yellow',
    },
    {
      id: 'e_d_slice_of_life_b_commerce_emperor',
      source: 'd_slice_of_life',
      target: 'b_commerce_emperor',
      label: 'Slicing up demons too',
      color: 'fuchsia',
    },
    {
      id: 'e_d_slice_of_life_b_immaculate',
      source: 'd_slice_of_life',
      target: 'b_immaculate',
      label: 'So slice, very life',
      color: 'green',
    },
    {
      id: 'e_d_crafting_trading_focus_d_theme',
      source: 'd_crafting_trading_focus',
      target: 'd_theme',
      label: 'I crave blood',
      color: 'orange',
    },
    {
      id: 'e_d_crafting_trading_focus_d_slice_of_life',
      source: 'd_crafting_trading_focus',
      target: 'd_slice_of_life',
      label: 'Yeah alright',
      color: 'sky',
    },
    {
      id: 'e_d_fanfic_of_b_system_override',
      source: 'd_fanfic_of',
      target: 'b_system_override',
      label: 'My BOI David Martinez',
      color: 'sky',
    },
    {
      id: 'e_d_fanfic_of_b_ghost_city',
      source: 'd_fanfic_of',
      target: 'b_ghost_city',
      label: 'All the existing characters, but the MC is new!',
      color: 'amber',
    },
    {
      id: 'e_d_with_plenty_of_d_we_exploring',
      source: 'd_with_plenty_of',
      target: 'd_we_exploring',
      label: 'Exploration',
      color: 'sky',
    },
    {
      id: 'e_d_with_plenty_of_d_in_one_or_build_one',
      source: 'd_with_plenty_of',
      target: 'd_in_one_or_build_one',
      label: 'Sects',
      color: 'violet',
    },
    {
      id: 'e_d_with_plenty_of_d_hell_or_africa',
      source: 'd_with_plenty_of',
      target: 'd_hell_or_africa',
      label: 'Conflict',
      color: 'orange',
    },
    {
      id: 'e_d_in_one_or_build_one_b_seventh_bridge',
      source: 'd_in_one_or_build_one',
      target: 'b_seventh_bridge',
      label: 'Build one',
      color: 'red',
    },
    {
      id: 'e_d_in_one_or_build_one_b_thousand_li',
      source: 'd_in_one_or_build_one',
      target: 'b_thousand_li',
      label: 'Trademark one',
      color: 'amber',
    },
    {
      id: 'e_d_in_one_or_build_one_d_how_do_you_like_your_ears',
      source: 'd_in_one_or_build_one',
      target: 'd_how_do_you_like_your_ears',
      label: 'Be in one',
      color: 'green',
    },
    {
      id: 'e_d_you_like_cards_d_crafting_trading_focus',
      source: 'd_you_like_cards',
      target: 'd_crafting_trading_focus',
      label: 'No.',
      color: 'blue',
    },
    {
      id: 'e_d_you_like_cards_b_jakes_market',
      source: 'd_you_like_cards',
      target: 'b_jakes_market',
      label: 'For half of a book, sure',
      color: 'amber',
    },
    {
      id: 'e_d_you_like_cards_b_casteless',
      source: 'd_you_like_cards',
      target: 'b_casteless',
      label: 'For the whole book!',
      color: 'green',
    },
    {
      id: 'e_d_fantasy_or_scifi_d_you_like_cards',
      source: 'd_fantasy_or_scifi',
      target: 'd_you_like_cards',
      label: 'Fantasy',
      color: 'red',
    },
    {
      id: 'e_d_fantasy_or_scifi_d_panam_or_judy',
      source: 'd_fantasy_or_scifi',
      target: 'd_panam_or_judy',
      label: 'Scifi',
      color: 'sky',
    },
    {
      id: 'e_d_how_much_fan_fiction_and_cross_d_fanfic_of',
      source: 'd_how_much_fan_fiction_and_cross',
      target: 'd_fanfic_of',
      label: 'Just Cyberpunk 2077',
      color: 'yellow',
    },
    {
      id: 'e_d_how_much_fan_fiction_and_cross_b_never_fade_away',
      source: 'd_how_much_fan_fiction_and_cross',
      target: 'b_never_fade_away',
      label: 'Everything.',
      color: 'purple',
    },
    {
      id: 'e_d_how_much_fan_fiction_and_cross_d_whoa_easy_there_so_a_strong_bu',
      source: 'd_how_much_fan_fiction_and_cross',
      target: 'd_whoa_easy_there_so_a_strong_bu',
      label: 'Damn I just want a fresh new world. Enough with crossovers and pop culture bullshit!',
      color: 'red',
    },
    {
      id: 'e_d_haaaave_you_read_cradle_b_cradle_2',
      source: 'd_haaaave_you_read_cradle',
      target: 'b_cradle',
      label: 'No',
      color: 'red',
    },
    {
      id: 'e_d_haaaave_you_read_cradle_d_have_you_read_a_lot_of_cultiva',
      source: 'd_haaaave_you_read_cradle',
      target: 'd_have_you_read_a_lot_of_cultiva',
      label: 'No shit',
      color: 'green',
    },
    {
      id: 'e_d_have_you_read_a_lot_of_cultiva_d_scifi_or_fantasy',
      source: 'd_have_you_read_a_lot_of_cultiva',
      target: 'd_scifi_or_fantasy',
      label: "I'll stop when I die",
      color: 'red',
    },
    {
      id: 'e_d_have_you_read_a_lot_of_cultiva_b_beware_chicken',
      source: 'd_have_you_read_a_lot_of_cultiva',
      target: 'b_beware_chicken',
      label: 'Yes, light-hearted, thanks.',
      color: 'orange',
    },
    {
      id: 'e_d_like_how_much_b_martial_peak',
      source: 'd_like_how_much',
      target: 'b_martial_peak',
      label: 'Fantasy... and then scifi',
      color: 'red',
    },
    {
      id: 'e_d_like_how_much_b_path_ascension',
      source: 'd_like_how_much',
      target: 'b_path_ascension',
      label: 'More scifi',
      color: 'sky',
    },
    {
      id: 'e_d_like_how_much_b_stargazers_war',
      source: 'd_like_how_much',
      target: 'b_stargazers_war',
      label: 'Hint of scifi',
      color: 'violet',
    },
    {
      id: 'e_d_scifi_or_fantasy_d_with_plenty_of',
      source: 'd_scifi_or_fantasy',
      target: 'd_with_plenty_of',
      label: 'Fantasy',
      color: 'green',
    },
    {
      id: 'e_d_scifi_or_fantasy_d_like_how_much',
      source: 'd_scifi_or_fantasy',
      target: 'd_like_how_much',
      label: 'Scifi',
      color: 'orange',
    },
    {
      id: 'e_d_scifi_or_fantasy_b_virtuous_sons',
      source: 'd_scifi_or_fantasy',
      target: 'b_virtuous_sons',
      label: 'Greco-roman',
      color: 'yellow',
    },
    {
      id: 'e_d_deliver_pain_via_weapons_or_ma_d_weapon_preference',
      source: 'd_deliver_pain_via_weapons_or_ma',
      target: 'd_weapon_preference',
      label: 'Weapons',
      color: 'green',
    },
    {
      id: 'e_d_deliver_pain_via_weapons_or_ma_b_industrial_magic',
      source: 'd_deliver_pain_via_weapons_or_ma',
      target: 'b_industrial_magic',
      label: 'Crafting',
      color: 'orange',
    },
    {
      id: 'e_d_deliver_pain_via_weapons_or_ma_b_apocalypse_parenting',
      source: 'd_deliver_pain_via_weapons_or_ma',
      target: 'b_apocalypse_parenting',
      label: 'Can we just stay alive please?',
      color: 'purple',
    },
    {
      id: 'e_d_deliver_pain_via_weapons_or_ma_d_opness',
      source: 'd_deliver_pain_via_weapons_or_ma',
      target: 'd_opness',
      label: 'Magic',
      color: 'sky',
    },
    {
      id: 'e_d_how_dat_b_welcome_multiverse',
      source: 'd_how_dat',
      target: 'b_welcome_multiverse',
      label: 'Skills, bruh',
      color: 'fuchsia',
    },
    {
      id: 'e_d_opness_d_howd_they_manage_that',
      source: 'd_opness',
      target: 'd_howd_they_manage_that',
      label: 'From day one',
      color: 'red',
    },
    {
      id: 'e_d_howd_they_manage_that_b_100th_run',
      source: 'd_howd_they_manage_that',
      target: 'b_100th_run',
      label: 'Done it before',
      color: 'green',
    },
    {
      id: 'e_d_howd_they_manage_that_b_system_universe',
      source: 'd_howd_they_manage_that',
      target: 'b_system_universe',
      label: 'System transition',
      color: 'sky',
    },
    {
      id: 'e_d_opness_that_d_how_dat',
      source: 'd_opness',
      target: 'd_how_dat',
      label: 'OP by first couple of books',
      color: 'purple',
    },
    {
      id: 'e_d_how_dat_d_you_got_this',
      source: 'd_how_dat',
      target: 'd_you_got_this',
      label: 'Ridiculously lucky drops',
      color: 'red',
    },
    {
      id: 'e_d_you_got_this_d_and_in_this_home_you',
      source: 'd_you_got_this',
      target: 'd_and_in_this_home_you',
      label: 'A secure home you can rest in',
      color: 'amber',
    },
    {
      id: 'e_d_and_in_this_home_you_b_travellers_trial',
      source: 'd_and_in_this_home_you',
      target: 'b_travellers_trial',
      label: 'Train, relax, and meditate',
      color: 'sky',
    },
    {
      id: 'e_d_and_in_this_home_you_b_discount_dan',
      source: 'd_and_in_this_home_you',
      target: 'b_discount_dan',
      label: "Watch your cult's NASCAR death races.",
      color: 'orange',
    },
    {
      id: 'e_d_how_dat_b_corruption_wielder_2',
      source: 'd_how_dat',
      target: 'b_corruption_wielder',
      label: 'Tutorial was fucked',
      color: 'orange',
    },
    {
      id: 'e_d_how_dat_b_accidental_champion',
      source: 'd_how_dat',
      target: 'b_accidental_champion',
      label: 'Achievements, bro',
      color: 'green',
    },
    {
      id: 'e_d_i_gotchu_fam_b_aura_overload',
      source: 'd_i_gotchu_fam',
      target: 'b_aura_overload',
      label: 'Cheers, guv',
      color: 'fuchsia',
    },
    {
      id: 'e_d_whoa_easy_there_so_a_strong_bu_d_i_gotchu_fam',
      source: 'd_whoa_easy_there_so_a_strong_bu',
      target: 'd_i_gotchu_fam',
      label: 'Yes! Is it really that hard?!',
      color: 'orange',
    },
    {
      id: 'e_d_panam_or_judy_d_you_like_cards',
      source: 'd_panam_or_judy',
      target: 'd_you_like_cards',
      label: 'Wat?',
      color: 'lime',
    },
    {
      id: 'e_d_panam_or_judy_d_op_protag',
      source: 'd_panam_or_judy',
      target: 'd_op_protag',
      label: 'They\re both the best.',
      color: 'yellow',
    },
    {
      id: 'e_d_panam_or_judy_d_wtf_dark_enough',
      source: 'd_panam_or_judy',
      target: 'd_wtf_dark_enough',
      label: 'River',
      color: 'orange',
    },
    {
      id: 'e_d_back_to_combat_training_then_b_art_adept',
      source: 'd_back_to_combat_training_then',
      target: 'b_art_adept',
      label: 'Force spells all day every day',
      color: 'red',
    },
    {
      id: 'e_d_back_to_combat_training_then_b_umbral_storm',
      source: 'd_back_to_combat_training_then',
      target: 'b_umbral_storm',
      label: 'Sect combat, yeah',
      color: 'sky',
    },
    {
      id: 'e_d_back_to_combat_training_then_b_best_friend_eldritch',
      source: 'd_back_to_combat_training_then',
      target: 'b_best_friend_eldritch',
      label: 'Eldritch friend',
      color: 'orange',
    },
    {
      id: 'e_d_op_protag_b_quest_academy',
      source: 'd_op_protag',
      target: 'b_quest_academy',
      label: 'SSSSS+ OP',
      color: 'amber',
    },
    {
      id: 'e_d_op_protag_d_how_much_fan_fiction_and_cross',
      source: 'd_op_protag',
      target: 'd_how_much_fan_fiction_and_cross',
      label: 'Yes!',
      color: 'orange',
    },
    {
      id: 'e_d_op_protag_d_female_mc',
      source: 'd_op_protag',
      target: 'd_female_mc',
      label: 'Nah, slower burn',
      color: 'green',
    },
    {
      id: 'e_d_wtf_dark_enough_b_changeling',
      source: 'd_wtf_dark_enough',
      target: 'b_changeling',
      label: 'DARKER',
      color: 'red',
    },
    {
      id: 'e_d_wtf_dark_enough_b_1pct_lifesteal',
      source: 'd_wtf_dark_enough',
      target: 'b_1pct_lifesteal',
      label: 'A really want to see someone suffer',
      color: 'fuchsia',
    },
    {
      id: 'e_d_sassy_ai_in_your_head_d_ai_can_spend_points_and_buy_yo',
      source: 'd_sassy_ai_in_your_head',
      target: 'd_ai_can_spend_points_and_buy_yo',
      label: 'Oh yeah',
      color: 'purple',
    },
    {
      id: 'e_d_sassy_ai_in_your_head_b_neon_dragons',
      source: 'd_sassy_ai_in_your_head',
      target: 'b_neon_dragons',
      label: 'Just a system, thanks',
      color: 'sky',
    },
    {
      id: 'e_d_ai_can_spend_points_and_buy_yo_b_cyber_dreams',
      source: 'd_ai_can_spend_points_and_buy_yo',
      target: 'b_cyber_dreams',
      label: 'Not yet',
      color: 'orange',
    },
    {
      id: 'e_d_ai_can_spend_points_and_buy_yo_b_stray_cat_strut',
      source: 'd_ai_can_spend_points_and_buy_yo',
      target: 'b_stray_cat_strut',
      label: "Only if it's cat themed",
      color: 'red',
    },
    { id: 'e_d_start_d_will_you_die', source: 'd_start', target: 'd_will_you_die', label: 'Hell yeah', color: 'amber' },
    {
      id: 'e_d_will_you_die_d_maybe_some_cultivation_instead',
      source: 'd_will_you_die',
      target: 'd_maybe_some_cultivation_instead',
      label: 'No, I will survive (Numbers not required)',
      color: 'green',
    },
    {
      id: 'e_d_will_you_die_d_system_apocalypse_or_isekai',
      source: 'd_will_you_die',
      target: 'd_system_apocalypse_or_isekai',
      label: 'Instant death (I want numbers)',
      color: 'orange',
    },
    {
      id: 'e_d_maybe_some_cultivation_instead_d_haaaave_you_read_cradle',
      source: 'd_maybe_some_cultivation_instead',
      target: 'd_haaaave_you_read_cradle',
      label: 'Yeah!',
      color: 'orange',
    },
    {
      id: 'e_d_maybe_some_cultivation_instead_d_okay_but_magic_schools_are_coo',
      source: 'd_maybe_some_cultivation_instead',
      target: 'd_okay_but_magic_schools_are_coo',
      label: 'Ew. No.',
      color: 'red',
    },
    {
      id: 'e_d_female_mc_d_sassy_ai_in_your_head',
      source: 'd_female_mc',
      target: 'd_sassy_ai_in_your_head',
      label: 'Yes',
      color: 'red',
    },
    {
      id: 'e_d_female_mc_d_should_romance_be_a_central_th',
      source: 'd_female_mc',
      target: 'd_should_romance_be_a_central_th',
      label: "Don't limit me to one MC!",
      color: 'amber',
    },
    {
      id: 'e_d_system_apocalypse_or_isekai_d_please_explain',
      source: 'd_system_apocalypse_or_isekai',
      target: 'd_please_explain',
      label: 'Other',
      color: 'green',
    },
    {
      id: 'e_d_please_explain_d_vrmmo_login_as',
      source: 'd_please_explain',
      target: 'd_vrmmo_login_as',
      label: 'Old school VRMMO, actually',
      color: 'green',
    },
    {
      id: 'e_d_vrmmo_login_as_b_awaken_online',
      source: 'd_vrmmo_login_as',
      target: 'b_awaken_online',
      label: 'An OP necromancer with a sheep god problem',
      color: 'violet',
    },
    {
      id: 'e_d_vrmmo_login_as_b_somnia',
      source: 'd_vrmmo_login_as',
      target: 'b_somnia',
      label: "A girl tangled up with the game's AIs",
      color: 'emerald',
    },
    {
      id: 'e_d_please_explain_d_fantasy_or_scifi',
      source: 'd_please_explain',
      target: 'd_fantasy_or_scifi',
      label: 'None of the above. Not hard.',
      color: 'blue',
    },
    {
      id: 'e_d_system_apocalypse_or_isekai_d_deliver_pain_via_weapons_or_ma',
      source: 'd_system_apocalypse_or_isekai',
      target: 'd_deliver_pain_via_weapons_or_ma',
      label: 'System apocalypse',
      color: 'red',
    },
    {
      id: 'e_d_system_apocalypse_or_isekai_d_humanity_is',
      source: 'd_system_apocalypse_or_isekai',
      target: 'd_humanity_is',
      label: 'Truck-kun is best-kun (isekai or portal fantasy)',
      color: 'amber',
    },
    {
      id: 'e_d_do_you_like_a_good_crafting_se_d_back_to_combat_training_then',
      source: 'd_do_you_like_a_good_crafting_se',
      target: 'd_back_to_combat_training_then',
      label: 'Not really',
      color: 'amber',
    },
    {
      id: 'e_d_do_you_like_a_good_crafting_se_d_crafting_companion',
      source: 'd_do_you_like_a_good_crafting_se',
      target: 'd_crafting_companion',
      label: 'YES',
      color: 'green',
    },
    {
      id: 'e_d_crafting_companion_b_arcane_ascension',
      source: 'd_crafting_companion',
      target: 'b_arcane_ascension',
      label: 'An analytical exploiter delving a magical spire',
      color: 'red',
    },
    {
      id: 'e_d_crafting_companion_b_enchanter',
      source: 'd_crafting_companion',
      target: 'b_enchanter',
      label: "An anxious tailor's son with a tasteful romance",
      color: 'emerald',
    },
    {
      id: 'e_d_crafting_companion_b_mother_learning',
      source: 'd_crafting_companion',
      target: 'b_mother_learning',
      label: 'A man-of-many-mornings stuck in a time loop',
      color: 'lime',
    },
    {
      id: 'e_d_do_you_like_a_good_crafting_se_d_gimme_the_gimmick',
      source: 'd_do_you_like_a_good_crafting_se',
      target: 'd_gimme_the_gimmick',
      label: 'A bit',
      color: 'sky',
    },
    {
      id: 'e_d_gimme_the_gimmick_b_mark_of_the_fool',
      source: 'd_gimme_the_gimmick',
      target: 'b_mark_of_the_fool',
      label: 'Learning is so hard its easy',
      color: 'sky',
    },
    {
      id: 'e_d_gimme_the_gimmick_b_archmage_coefficient',
      source: 'd_gimme_the_gimmick',
      target: 'b_archmage_coefficient',
      label: 'You can see magic. And autism.',
      color: 'purple',
    },
    {
      id: 'e_d_pick_between_b_scholomance',
      source: 'd_pick_between',
      target: 'b_scholomance',
      label: 'Demons are trying to eat you',
      color: 'orange',
    },
    {
      id: 'e_d_pick_between_d_with_a_focus_on',
      source: 'd_pick_between',
      target: 'd_with_a_focus_on',
      label: 'Just want scifi',
      color: 'sky',
    },
    {
      id: 'e_d_humanity_is_d_by_how_much',
      source: 'd_humanity_is',
      target: 'd_by_how_much',
      label: 'Overrated.',
      color: 'red',
    },
    {
      id: 'e_d_humanity_is_d_but_i_want_a_focus_on',
      source: 'd_humanity_is',
      target: 'd_but_i_want_a_focus_on',
      label: 'Alright I guess',
      color: 'green',
    },
    {
      id: 'e_d_by_how_much_d_so_youre_thinking',
      source: 'd_by_how_much',
      target: 'd_so_youre_thinking',
      label: 'A bit overrated',
      color: 'orange',
    },
    {
      id: 'e_d_by_how_much_d_what_s_better',
      source: 'd_by_how_much',
      target: 'd_what_s_better',
      label: 'Super overrated',
      color: 'yellow',
    },
    {
      id: 'e_d_so_youre_thinking_b_salvos',
      source: 'd_so_youre_thinking',
      target: 'b_salvos',
      label: 'Demons',
      color: 'red',
    },
    {
      id: 'e_d_so_youre_thinking_b_nova_roma',
      source: 'd_so_youre_thinking',
      target: 'b_nova_roma',
      label: 'AI',
      color: 'blue',
    },
    {
      id: 'e_d_with_a_focus_on_b_titan_hoppers',
      source: 'd_with_a_focus_on',
      target: 'b_titan_hoppers',
      label: 'Scavenging',
      color: 'green',
    },
    {
      id: 'e_d_with_a_focus_on_b_super_supportive',
      source: 'd_with_a_focus_on',
      target: 'b_super_supportive',
      label: 'Superhero academy',
      color: 'yellow',
    },
    {
      id: 'e_d_with_a_focus_on_b_starbreaker',
      source: 'd_with_a_focus_on',
      target: 'b_starbreaker',
      label: 'COMBAT MORE COMBAT EVEN MORE COMBAT',
      color: 'red',
    },
    {
      id: 'e_d_with_a_focus_on_b_iron_prince',
      source: 'd_with_a_focus_on',
      target: 'b_iron_prince',
      label: 'Virtual tournament combat',
      color: 'violet',
    },
    {
      id: 'e_d_should_romance_be_a_central_th_b_cybergene',
      source: 'd_should_romance_be_a_central_th',
      target: 'b_cybergene',
      label: 'Small romance only!',
      color: 'purple',
    },
    {
      id: 'e_d_should_romance_be_a_central_th_b_neon_dust',
      source: 'd_should_romance_be_a_central_th',
      target: 'b_neon_dust',
      label: 'Yes please!',
      color: 'green',
    },
    {
      id: 'e_d_what_s_better_d_arms_are',
      source: 'd_what_s_better',
      target: 'd_arms_are',
      label: 'Something without arms',
      color: 'green',
    },
    {
      id: 'e_d_arms_are_d_pick_your_harmless_creature',
      source: 'd_arms_are',
      target: 'd_pick_your_harmless_creature',
      label: 'Stupid',
      color: 'green',
    },
    {
      id: 'e_d_pick_your_harmless_creature_b_demon_tree',
      source: 'd_pick_your_harmless_creature',
      target: 'b_demon_tree',
      label: 'Trees',
      color: 'green',
    },
    {
      id: 'e_d_pick_your_harmless_creature_b_all_the_dust',
      source: 'd_pick_your_harmless_creature',
      target: 'b_all_the_dust',
      label: 'Robovacs',
      color: 'purple',
    },
    {
      id: 'e_d_pick_your_harmless_creature_b_chrysalis',
      source: 'd_pick_your_harmless_creature',
      target: 'b_chrysalis',
      label: 'Ants. FOR THE COLONY.',
      color: 'lime',
    },
    {
      id: 'e_d_arms_are_d_youd_prefer',
      source: 'd_arms_are',
      target: 'd_youd_prefer',
      label: 'Overrated',
      color: 'lime',
    },
    {
      id: 'e_d_youd_prefer_b_merchant_crab',
      source: 'd_youd_prefer',
      target: 'b_merchant_crab',
      label: 'Pincers',
      color: 'lime',
    },
    {
      id: 'e_d_youd_prefer_b_queen_mud',
      source: 'd_youd_prefer',
      target: 'b_queen_mud',
      label: 'Legs you can use as arms.',
      color: 'orange',
    },
    {
      id: 'e_d_arms_are_d_and_should_be',
      source: 'd_arms_are',
      target: 'd_and_should_be',
      label: 'Pretty handy actually',
      color: 'red',
    },
    {
      id: 'e_d_and_should_be_b_vainqueur',
      source: 'd_and_should_be',
      target: 'b_vainqueur',
      label: 'Scaly',
      color: 'red',
    },
    {
      id: 'e_d_and_should_be_b_threadbare',
      source: 'd_and_should_be',
      target: 'b_threadbare',
      label: 'Soft',
      color: 'amber',
    },
    {
      id: 'e_d_with_extra_focus_on_d_team_squad',
      source: 'd_with_extra_focus_on',
      target: 'd_team_squad',
      label: 'Team combat',
      color: 'red',
    },
    {
      id: 'e_d_team_squad_b_shattered_gods',
      source: 'd_team_squad',
      target: 'b_shattered_gods',
      label: 'A boy and his ratman, conquering catalysts',
      color: 'teal',
    },
    {
      id: 'e_d_team_squad_b_eternal_ephemera',
      source: 'd_team_squad',
      target: 'b_eternal_ephemera',
      label: 'A boy, a panda, and an orca-girl walk into a dance class',
      color: 'orange',
    },
    {
      id: 'e_d_with_extra_focus_on_b_edge_cases',
      source: 'd_with_extra_focus_on',
      target: 'b_edge_cases',
      label: 'Dungeons and FRIENDSHIP',
      color: 'sky',
    },
    {
      id: 'e_d_okay_but_magic_schools_are_coo_d_pick_between',
      source: 'd_okay_but_magic_schools_are_coo',
      target: 'd_pick_between',
      label: 'Yeah, but as a setting. No essays.',
      color: 'yellow',
    },
    {
      id: 'e_d_okay_but_magic_schools_are_coo_d_how_much_focus_on_learning',
      source: 'd_okay_but_magic_schools_are_coo',
      target: 'd_how_much_focus_on_learning',
      label: 'Inject them into my veins',
      color: 'green',
    },
    {
      id: 'e_d_okay_but_magic_schools_are_coo_d_how_about_time_loops_time_loop',
      source: 'd_okay_but_magic_schools_are_coo',
      target: 'd_how_about_time_loops_time_loop',
      label: 'Eh. Not always.',
      color: 'orange',
    },
    {
      id: 'e_d_how_much_focus_on_learning_d_do_you_like_a_good_crafting_se',
      source: 'd_how_much_focus_on_learning',
      target: 'd_do_you_like_a_good_crafting_se',
      label: 'Education is paramount.',
      color: 'yellow',
    },
    {
      id: 'e_d_how_much_focus_on_learning_b_guild_mage',
      source: 'd_how_much_focus_on_learning',
      target: 'b_guild_mage',
      label: 'Eh. A bit of school, a lot of not',
      color: 'orange',
    },
    {
      id: 'e_d_how_much_focus_on_learning_b_mage_errant',
      source: 'd_how_much_focus_on_learning',
      target: 'b_mage_errant',
      label: 'Learn by doing! Spread your wings!',
      color: 'violet',
    },
    {
      id: 'e_d_but_i_want_a_focus_on_d_with_extra_focus_on',
      source: 'd_but_i_want_a_focus_on',
      target: 'd_with_extra_focus_on',
      label: 'A group',
      color: 'yellow',
    },
    {
      id: 'e_d_but_i_want_a_focus_on_d_mc_specialises_in',
      source: 'd_but_i_want_a_focus_on',
      target: 'd_mc_specialises_in',
      label: "A strong independent woman who don't need no man",
      color: 'pink',
    },
    {
      id: 'e_d_but_i_want_a_focus_on_d_pick_your_setting',
      source: 'd_but_i_want_a_focus_on',
      target: 'd_pick_your_setting',
      label: 'MAN',
      color: 'red',
    },
    {
      id: 'e_d_pick_your_gimmick_d_shapeshift_into',
      source: 'd_pick_your_gimmick',
      target: 'd_shapeshift_into',
      label: 'Shapeshifting',
      color: 'violet',
    },
    {
      id: 'e_d_shapeshift_into_b_odyssey_ethereal',
      source: 'd_shapeshift_into',
      target: 'b_odyssey_ethereal',
      label: 'Cute things in a tower climber',
      color: 'red',
    },
    {
      id: 'e_d_shapeshift_into_b_none_shall_remain',
      source: 'd_shapeshift_into',
      target: 'b_none_shall_remain',
      label: 'Eldritch flesh in a forest of monsters',
      color: 'fuchsia',
    },
    {
      id: 'e_d_pick_your_gimmick_b_azarinth_healer',
      source: 'd_pick_your_gimmick',
      target: 'b_azarinth_healer',
      label: 'Regeneration',
      color: 'amber',
    },
    {
      id: 'e_d_pick_your_gimmick_b_calamitous_bob',
      source: 'd_pick_your_gimmick',
      target: 'b_calamitous_bob',
      label: 'Black mana... but not necromancy.',
      color: 'orange',
    },
    {
      id: 'e_d_pick_your_gimmick_b_saintess_skel',
      source: 'd_pick_your_gimmick',
      target: 'b_saintess_skel',
      label: 'Necromancy',
      color: 'red',
    },
    {
      id: 'e_d_mc_specialises_in_d_pick_your_gimmick',
      source: 'd_mc_specialises_in',
      target: 'd_pick_your_gimmick',
      label: 'Violence',
      color: 'yellow',
    },
    {
      id: 'e_d_mc_specialises_in_d_specifically',
      source: 'd_mc_specialises_in',
      target: 'd_specifically',
      label: '... not violence?',
      color: 'lime',
    },
    {
      id: 'e_d_specifically_b_dragons_eye_moons',
      source: 'd_specifically',
      target: 'b_dragons_eye_moons',
      label: 'Healing',
      color: 'sky',
    },
    {
      id: 'e_d_specifically_b_cinnamon_bun',
      source: 'd_specifically',
      target: 'b_cinnamon_bun',
      label: 'Making friends',
      color: 'red',
    },
    {
      id: 'e_d_pick_your_setting_2_d_slow_burn_or_power_fantasy',
      source: 'd_pick_your_setting_2',
      target: 'd_slow_burn_or_power_fantasy',
      label: 'Original Fantasy',
      color: 'emerald',
    },
    {
      id: 'e_d_pick_your_setting_2_d_movie_analogy',
      source: 'd_pick_your_setting_2',
      target: 'd_movie_analogy',
      label: 'Sci-fi',
      color: 'sky',
    },
    {
      id: 'e_d_pick_your_setting_2_d_but_this_world',
      source: 'd_pick_your_setting_2',
      target: 'd_but_this_world',
      label: 'This world',
      color: 'orange',
    },
    { id: 'e_d_movie_analogy_b_godclads', source: 'd_movie_analogy', target: 'b_godclads', label: 'Saw', color: 'red' },
    {
      id: 'e_d_movie_analogy_b_red_rising',
      source: 'd_movie_analogy',
      target: 'b_red_rising',
      label: 'Space Gladiator Hunger Games',
      color: 'orange',
    },
    {
      id: 'e_d_movie_analogy_b_lightblade',
      source: 'd_movie_analogy',
      target: 'b_lightblade',
      label: 'Inception + The Matrix',
      color: 'amber',
    },
    {
      id: 'e_d_movie_analogy_b_wish_upon_stars',
      source: 'd_movie_analogy',
      target: 'b_wish_upon_stars',
      label: 'CyberAladdin',
      color: 'violet',
    },
    {
      id: 'e_d_but_this_world_b_fifty_shades',
      source: 'd_but_this_world',
      target: 'b_fifty_shades',
      label: 'Abuse is cool!',
      color: 'pink',
    },
    {
      id: 'e_d_how_about_time_loops_time_loop_d_pick_your_setting_2',
      source: 'd_how_about_time_loops_time_loop',
      target: 'd_pick_your_setting_2',
      label: 'I hate everything.',
      color: 'yellow',
    },
    {
      id: 'e_d_how_about_time_loops_time_loop_d_organization_or_character_poli',
      source: 'd_how_about_time_loops_time_loop',
      target: 'd_organization_or_character_poli',
      label: 'The coolest',
      color: 'emerald',
    },
    {
      id: 'e_d_how_about_time_loops_time_loop_d_futuristic_sci_fi',
      source: 'd_how_about_time_loops_time_loop',
      target: 'd_futuristic_sci_fi',
      label: 'I like time skips, not time loops',
      color: 'sky',
    },
    {
      id: 'e_d_organization_or_character_poli_b_dear_spellbook',
      source: 'd_organization_or_character_poli',
      target: 'b_dear_spellbook',
      label: 'No.',
      color: 'violet',
    },
    {
      id: 'e_d_organization_or_character_poli_d_small_doses_time',
      source: 'd_organization_or_character_poli',
      target: 'd_small_doses_time',
      label: 'In small doses',
      color: 'amber',
    },
    {
      id: 'e_d_small_doses_time_b_desolada',
      source: 'd_small_doses_time',
      target: 'b_desolada',
      label: 'A grimdark hour-reverser hunting demons',
      color: 'red',
    },
    {
      id: 'e_d_small_doses_time_b_perfect_run',
      source: 'd_small_doses_time',
      target: 'b_perfect_run',
      label: 'A save-scumming superhero ensemble',
      color: 'orange',
    },
    {
      id: 'e_d_organization_or_character_poli_b_remonarch',
      source: 'd_organization_or_character_poli',
      target: 'b_remonarch',
      label: 'Yea bo!',
      color: 'red',
    },
    {
      id: 'e_d_slow_burn_or_power_fantasy_d_what_about_tone_something_ligh',
      source: 'd_slow_burn_or_power_fantasy',
      target: 'd_what_about_tone_something_ligh',
      label: 'Slowish burn',
      color: 'pink',
    },
    {
      id: 'e_d_slow_burn_or_power_fantasy_b_legend_arch_magus',
      source: 'd_slow_burn_or_power_fantasy',
      target: 'b_legend_arch_magus',
      label: 'Ridiculous power fantasy',
      color: 'red',
    },
    {
      id: 'e_d_pick_your_setting_d_is_combat_the_primary_focus',
      source: 'd_pick_your_setting',
      target: 'd_is_combat_the_primary_focus',
      label: 'Fantasy',
      color: 'sky',
    },
    {
      id: 'e_d_pick_your_setting_d_time_loops_or_crunch',
      source: 'd_pick_your_setting',
      target: 'd_time_loops_or_crunch',
      label: 'Vidya games',
      color: 'amber',
    },
    {
      id: 'e_d_what_about_tone_something_ligh_b_millenial_mage',
      source: 'd_what_about_tone_something_ligh',
      target: 'b_millenial_mage',
      label: 'Chill and fun... to start with',
      color: 'emerald',
    },
    {
      id: 'e_d_what_about_tone_something_ligh_d_parody_flavour',
      source: 'd_what_about_tone_something_ligh',
      target: 'd_parody_flavour',
      label: 'Parody please',
      color: 'sky',
    },
    {
      id: 'e_d_parody_flavour_b_rock_falls',
      source: 'd_parody_flavour',
      target: 'b_rock_falls',
      label: 'Cultivation tropes, but the MC is a literal stone',
      color: 'red',
    },
    {
      id: 'e_d_parody_flavour_b_how_to_defeat_demon_king',
      source: 'd_parody_flavour',
      target: 'b_how_to_defeat_demon_king',
      label: 'Zelda fetch-quests with a Bag Mage hero',
      color: 'cyan',
    },
    {
      id: 'e_d_what_about_tone_something_ligh_d_mtg_is',
      source: 'd_what_about_tone_something_ligh',
      target: 'd_mtg_is',
      label: 'A serious settings',
      color: 'orange',
    },
    {
      id: 'e_d_is_combat_the_primary_focus_d_i_prefer_mcs_who_are',
      source: 'd_is_combat_the_primary_focus',
      target: 'd_i_prefer_mcs_who_are',
      label: 'Yes',
      color: 'amber',
    },
    {
      id: 'e_d_is_combat_the_primary_focus_d_vibe_check',
      source: 'd_is_combat_the_primary_focus',
      target: 'd_vibe_check',
      label: 'There can be other things',
      color: 'orange',
    },
    {
      id: 'e_d_are_weird_creature_companions_b_hwfwm',
      source: 'd_are_weird_creature_companions',
      target: 'b_hwfwm',
      label: 'I like slugs. Buckets of them.',
      color: 'purple',
    },
    {
      id: 'e_d_are_weird_creature_companions_b_unbound',
      source: 'd_are_weird_creature_companions',
      target: 'b_unbound',
      label: 'I like chimeras',
      color: 'red',
    },
    {
      id: 'e_d_are_weird_creature_companions_b_bog_standard',
      source: 'd_are_weird_creature_companions',
      target: 'b_bog_standard',
      label: 'I just want a little dragon',
      color: 'lime',
    },
    {
      id: 'e_d_are_weird_creature_companions_d_whats_your_kink',
      source: 'd_are_weird_creature_companions',
      target: 'd_whats_your_kink',
      label: 'Imma need you to define "weird"',
      color: 'amber',
    },
    {
      id: 'e_d_i_prefer_mcs_who_are_d_do_you_scream_for_joy_every_ti',
      source: 'd_i_prefer_mcs_who_are',
      target: 'd_do_you_scream_for_joy_every_ti',
      label: 'Weak to strong',
      color: 'lime',
    },
    {
      id: 'e_d_i_prefer_mcs_who_are_d_alright_you_do_you_buddy',
      source: 'd_i_prefer_mcs_who_are',
      target: 'd_alright_you_do_you_buddy',
      label: 'Unkillable cockroaches',
      color: 'red',
    },
    {
      id: 'e_d_i_prefer_mcs_who_are_d_i_like',
      source: 'd_i_prefer_mcs_who_are',
      target: 'd_i_like',
      label: 'So strong',
      color: 'orange',
    },
    {
      id: 'e_d_do_you_scream_for_joy_every_ti_b_noobtown',
      source: 'd_do_you_scream_for_joy_every_ti',
      target: 'b_noobtown',
      label: 'I love pop culture almost as much as I love capitalism',
      color: 'red',
    },
    {
      id: 'e_d_do_you_scream_for_joy_every_ti_d_are_weird_creature_companions',
      source: 'd_do_you_scream_for_joy_every_ti',
      target: 'd_are_weird_creature_companions',
      label: "I'd prefer a balanced story too...",
      color: 'sky',
    },
    {
      id: 'e_d_do_you_scream_for_joy_every_ti_b_chaos_seeds',
      source: 'd_do_you_scream_for_joy_every_ti',
      target: 'b_chaos_seeds',
      label: 'Literally shit myself with joy',
      color: 'orange',
    },
    {
      id: 'e_d_time_loops_or_crunch_b_minute_mage',
      source: 'd_time_loops_or_crunch',
      target: 'b_minute_mage',
      label: 'Time loops!',
      color: 'sky',
    },
    {
      id: 'e_d_time_loops_or_crunch_b_completionist',
      source: 'd_time_loops_or_crunch',
      target: 'b_completionist',
      label: 'Video game crunch',
      color: 'red',
    },
    {
      id: 'e_d_mtg_is_b_all_the_skills',
      source: 'd_mtg_is',
      target: 'b_all_the_skills',
      label: "For Nerds... and I'm a nerd",
      color: 'emerald',
    },
    {
      id: 'e_d_mtg_is_d_pick_your_backdrop',
      source: 'd_mtg_is',
      target: 'd_pick_your_backdrop',
      label: 'Uh? A mortgage? Meeting?',
      color: 'sky',
    },
    {
      id: 'e_d_alright_you_do_you_buddy_b_mage_tank',
      source: 'd_alright_you_do_you_buddy',
      target: 'b_mage_tank',
      color: 'orange',
    },
    {
      id: 'e_d_whats_your_kink_b_pit_fighter',
      source: 'd_whats_your_kink',
      target: 'b_pit_fighter',
      label: 'Helping others',
      color: 'sky',
    },
    {
      id: 'e_d_whats_your_kink_b_outcast',
      source: 'd_whats_your_kink',
      target: 'b_outcast',
      label: 'Masochism',
      color: 'red',
    },
    {
      id: 'e_d_pick_your_backdrop_b_chronicles_druss',
      source: 'd_pick_your_backdrop',
      target: 'b_chronicles_druss',
      label: 'Black and white',
      color: 'orange',
    },
    {
      id: 'e_d_pick_your_backdrop_b_lightbringer',
      source: 'd_pick_your_backdrop',
      target: 'b_lightbringer',
      label: 'Many shades of colours',
      color: 'amber',
    },
    {
      id: 'e_d_pick_your_backdrop_d_interesting_tell_me_more',
      source: 'd_pick_your_backdrop',
      target: 'd_interesting_tell_me_more',
      label: 'Complex',
      color: 'violet',
    },
    {
      id: 'e_d_interesting_tell_me_more_b_practical_evil',
      source: 'd_interesting_tell_me_more',
      target: 'b_practical_evil',
      label: 'An evil path can lead to a greater good',
      color: 'emerald',
    },
    {
      id: 'e_d_interesting_tell_me_more_b_night_angel',
      source: 'd_interesting_tell_me_more',
      target: 'b_night_angel',
      label: 'Are assassins even actually evil?',
      color: 'yellow',
    },
    {
      id: 'e_d_futuristic_sci_fi_b_bobiverse',
      source: 'd_futuristic_sci_fi',
      target: 'b_bobiverse',
      label: 'Yes',
      color: 'orange',
    },
    {
      id: 'e_d_futuristic_sci_fi_b_skitterdoc',
      source: 'd_futuristic_sci_fi',
      target: 'b_skitterdoc',
      label: 'Yes, but cyberpunk',
      color: 'red',
    },
    {
      id: 'e_d_futuristic_sci_fi_b_systema_delenda_est',
      source: 'd_futuristic_sci_fi',
      target: 'b_systema_delenda_est',
      label: 'Yes, posthumanity against the System!',
      color: 'sky',
    },
    {
      id: 'e_d_i_like_b_sovereign_soul',
      source: 'd_i_like',
      target: 'b_sovereign_soul',
      label: 'Otters',
      color: 'lime',
    },
    { id: 'e_d_i_like_b_dao_magic', source: 'd_i_like', target: 'b_dao_magic', label: 'Being edgy', color: 'amber' },
    {
      id: 'e_d_i_like_b_last_physicist',
      source: 'd_i_like',
      target: 'b_last_physicist',
      label: 'Special relativity',
      color: 'sky',
    },
    {
      id: 'e_d_vibe_check_b_eight',
      source: 'd_vibe_check',
      target: 'b_eight',
      label: 'Survive',
      color: 'amber',
    },
    {
      id: 'e_d_vibe_check_d_chill_sprinkle',
      source: 'd_vibe_check',
      target: 'd_chill_sprinkle',
      label: 'Chill',
      color: 'sky',
    },
    {
      id: 'e_d_vibe_check_d_be_specific',
      source: 'd_vibe_check',
      target: 'd_be_specific',
      label: 'Craft',
      color: 'teal',
    },
    {
      id: 'e_d_vibe_check_d_thank_god_youre_a',
      source: 'd_vibe_check',
      target: 'd_thank_god_youre_a',
      label: 'Fightish',
      color: 'violet',
    },
    {
      id: 'e_d_chill_sprinkle_b_heretical_fishing',
      source: 'd_chill_sprinkle',
      target: 'b_heretical_fishing',
      label: 'Salt of my fish',
      color: 'sky',
    },
    {
      id: 'e_d_chill_sprinkle_b_just_add_mana',
      source: 'd_chill_sprinkle',
      target: 'b_just_add_mana',
      label: 'Sass',
      color: 'pink',
    },
    {
      id: 'e_d_thank_god_youre_a_b_reincarnated_farmer',
      source: 'd_thank_god_youre_a',
      target: 'b_reincarnated_farmer',
      label: 'Farmer',
      color: 'emerald',
    },
    {
      id: 'e_d_thank_god_youre_a_d_dungeons_id_love_to',
      source: 'd_thank_god_youre_a',
      target: 'd_dungeons_id_love_to',
      label: 'Dungeon',
      color: 'green',
    },
    {
      id: 'e_d_thank_god_youre_a_d_acredited_right',
      source: 'd_thank_god_youre_a',
      target: 'd_acredited_right',
      label: 'Teacher',
      color: 'yellow',
    },
    {
      id: 'e_d_acredited_right_b_elydes',
      source: 'd_acredited_right',
      target: 'b_elydes',
      label: "No, I'm 3 years old.",
      color: 'violet',
    },
    {
      id: 'e_d_acredited_right_b_runebound_professor',
      source: 'd_acredited_right',
      target: 'b_runebound_professor',
      label: 'Literally a fraud',
      color: 'red',
    },
    {
      id: 'e_d_acredited_right_b_antimage',
      source: 'd_acredited_right',
      target: 'b_antimage',
      label: 'Actually a scientist',
      color: 'orange',
    },
    {
      id: 'e_d_be_specific_b_chaotic_craftsman',
      source: 'd_be_specific',
      target: 'b_chaotic_craftsman',
      label: 'Blacksmithing and enchanting with BIG BRAIN',
      color: 'violet',
    },
    {
      id: 'e_d_be_specific_b_runic_artist',
      source: 'd_be_specific',
      target: 'b_runic_artist',
      label: 'Crafting is but art, and the best art is with a paintbrush',
      color: 'amber',
    },
    {
      id: 'e_d_dungeon_s_focus_is_b_divine_dungeon',
      source: 'd_dungeon_s_focus_is',
      target: 'b_divine_dungeon',
      label: 'flying',
      color: 'sky',
    },
    {
      id: 'e_d_dungeon_s_focus_is_b_reluctant_dungeon',
      source: 'd_dungeon_s_focus_is',
      target: 'b_reluctant_dungeon',
      label: 'being left alone',
      color: 'emerald',
    },
    {
      id: 'e_d_dungeons_id_love_to_b_daily_grind',
      source: 'd_dungeons_id_love_to',
      target: 'b_daily_grind',
      label: 'explore one',
      color: 'yellow',
    },
    {
      id: 'e_d_dungeons_id_love_to_d_dungeon_s_focus_is',
      source: 'd_dungeons_id_love_to',
      target: 'd_dungeon_s_focus_is',
      label: 'be one',
      color: 'violet',
    },
    {
      id: 'e_d_dungeons_id_love_to_d_its_gonna_be',
      source: 'd_dungeons_id_love_to',
      target: 'd_its_gonna_be',
      label: 'climb one',
      color: 'amber',
    },
    {
      id: 'e_d_dungeons_id_love_to_b_rogue_dungeon',
      source: 'd_dungeons_id_love_to',
      target: 'b_rogue_dungeon',
      label: 'be a minion in one',
      color: 'orange',
    },
    {
      id: 'e_d_dungeons_id_love_to_b_dungeon_tour_guide',
      source: 'd_dungeons_id_love_to',
      target: 'b_dungeon_tour_guide',
      label: 'run one',
      color: 'lime',
    },
    {
      id: 'e_d_dungeons_id_love_to_b_solo_levelling',
      source: 'd_dungeons_id_love_to',
      target: 'b_solo_levelling',
      label: 'die in one',
      color: 'red',
    },
    {
      id: 'e_d_deliver_pain_via_weapons_or_ma_b_buymort',
      source: 'd_deliver_pain_via_weapons_or_ma',
      target: 'b_buymort',
      label: 'The whole economy is a weapon',
      color: 'orange',
    },
    {
      id: 'e_d_dungeon_s_focus_is_b_dungeon_of_knowledge',
      source: 'd_dungeon_s_focus_is',
      target: 'b_dungeon_of_knowledge',
      label: 'defeating an ancient Lich',
      color: 'purple',
    },
    {
      id: 'e_d_epic_fantasy_or_traditional_cu_b_ironbound',
      source: 'd_epic_fantasy_or_traditional_cu',
      target: 'b_ironbound',
      label: 'Fantasy Roman legion cultivation bro',
      color: 'red',
    },
    {
      id: 'e_d_so_youre_thinking_b_max_level_archmage',
      source: 'd_so_youre_thinking',
      target: 'b_max_level_archmage',
      label: 'MMO Demon (not VRMMO)',
      color: 'fuchsia',
    },
    {
      id: 'e_d_small_doses_time_b_hundred_reigns',
      source: 'd_small_doses_time',
      target: 'b_hundred_reigns',
      label: 'Become the evil overlord 100 times.',
      color: 'amber',
    },
    {
      id: 'e_d_its_gonna_be_b_legend_william',
      source: 'd_its_gonna_be',
      target: 'b_legend_william',
      label: 'Legendary',
      color: 'amber',
    },
    {
      id: 'e_d_its_gonna_be_b_tower_apocalypse',
      source: 'd_its_gonna_be',
      target: 'b_tower_apocalypse',
      label: 'Alright I guess',
      color: 'amber',
    },
    {
      id: 'e_d_be_specific_b_turret_mage',
      source: 'd_be_specific',
      target: 'b_turret_mage',
      label: 'Guns, turrets, and power armour',
      color: 'orange',
    },
    // Level One God — weird creature companions, "what's your kink" branch
    {
      id: 'e_d_whats_your_kink_b_level_one_god',
      source: 'd_whats_your_kink',
      target: 'b_level_one_god',
      label: 'Hairy voyeurism',
      color: 'indigo',
    },
    // Greatest Archmage — chill science-exploit branch, social anxiety flavour
    {
      id: 'e_d_chill_sprinkle_b_greatest_archmage',
      source: 'd_chill_sprinkle',
      target: 'b_greatest_archmage',
      label: 'Social anxiety',
      color: 'green',
    },
    // Terminate the Other World — female-lead isekai, violence gimmick: dual system exploitation
    {
      id: 'e_d_pick_your_gimmick_b_terminate_other_world',
      source: 'd_pick_your_gimmick',
      target: 'b_terminate_other_world',
      label: 'Cyborg + dungeon core',
      color: 'cyan',
    },
    // Keiran: The Eternal Mage — OP magic, slow rebuild from reincarnation weakness
    {
      id: 'e_d_how_dat_b_keiran_eternal_mage',
      source: 'd_how_dat',
      target: 'b_keiran_eternal_mage',
      label: 'Reincarnated archmage',
      color: 'sky',
    },
  ],
};
